pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'uname -a'
            }
        }
    }
}
 stage('Main Branch') {
            when {
                expression { env.BRANCH_NAME == 'main' }
            }
            steps {
                script {
                    echo 'this is the main branch'
                }
            }
        }
    }
}
